### ISSUE TITLE
Could you provide the checkpoint trained on the crosstask dataset?

### ISSUE THREAD

**Issue by xuangch** [ZijiaLewisLu/ICCV21-TASL#5]
Hi,
Thanks for your nice work! The training speed on crosstask is too slow, and I only completed less than 1/5 of the training epoch in 24 hours. Could you provide the checkpoint for fast evaluation? Thank you very much : )

**Comment by ZijiaLewisLu** [comment]
Hi,

Thanks for your interest in our work.

Unfortunately, the training time is long on Crosstask due to its long video length and the complexity of Viterbi decoding. If you want, you can play around with the `frame_sampling` parameter of Viterbi decoding to improve speed. I did not maintain the model checkpoint by now.
